use vector of vectors instead of unique pointer
sina-rostami/Reverse_costumizedGameOfLife pull request #40
Opened 2020-09-09 10:53 UTC by sina-rostami

First I used one vector instead of unique pointer, I faced with 
```
cannot convert ‘std::vector<bool>::reference*’ {aka ‘std::_Bit_reference*’} to ‘bool*’ in initialization
```
in index operator overloading.
then I decided to use vector of vectors and I think it's more readable in code.
but a bit slower...

2020-09-09 18:37 UTC, IYP-Programer-Yeah requested changes

2020-09-09 18:37 UTC, IYP-Programer-Yeah commented on Array2D.h
> +  vector<vector<T>> vc;
No, consider vector<T> instead of vector<vector<t>>.
Contiguous memory.

2020-09-09 20:45 UTC, IYP-Programer-Yeah requested changes

2020-09-09 20:45 UTC, IYP-Programer-Yeah commented on Array2D.hpp
> +  Array2D<T> &operator=(const Array2D<T> &other) {
not needed

2020-09-09 20:45 UTC, IYP-Programer-Yeah commented on Array2D.hpp
> +  Array2D(const Array2D<T> &other)
not needed

2020-09-09 20:45 UTC, IYP-Programer-Yeah commented on Gol.cpp
> +#include <unistd.h>
what is this included for?

2020-09-09 20:45 UTC, IYP-Programer-Yeah commented on Gol.cpp
> +    std::size_t max_size =
const?

2020-09-09 20:45 UTC, IYP-Programer-Yeah commented on Array2D.hpp
> +using std::vector;
almost always avoid using, they are rarely OK.

2020-09-10 07:20 UTC, sina-rostami commented on Gol.cpp
> +#include <unistd.h>
I was testing something

2020-09-10 07:21 UTC, sina-rostami commented on Array2D.hpp
> +  Array2D(const Array2D<T> &other)
which one? copy constructor?

2020-09-10 07:21 UTC, sina-rostami commented on Gol.cpp
> +    std::size_t max_size =
yes it's better to be const...

2020-09-10 07:22 UTC, sina-rostami commented on Array2D.hpp
> +using std::vector;
OK

2020-09-10 07:40 UTC, sina-rostami commented on Array2D.hpp
> -  Array2D<T> &operator=(const Array2D<T> &other) {
I think it is ok to use compiler generated copy assignment for the case.

2020-09-11 07:24 UTC, IYP-Programer-Yeah requested changes

2020-09-11 07:24 UTC, IYP-Programer-Yeah commented on .vscode/settings.json
> +    "files.associations": {
You probably dont wanna push this

2020-09-11 07:24 UTC, IYP-Programer-Yeah commented on Gol.cpp
> +    const std::size_t MAX_SIZE =
Why did you change the naming convention?

2020-09-11 08:31 UTC, merged